language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"  # 3.8 development branch

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

before_install:
  - mkdir $PWD/sea_battle/logging/
  - touch $PWD/sea_battle/logging/sb_logger_debug.log

install:
  - pipenv install -d

env:
  global:
    - PGPORT=5432

script:
  - export PYTHONPATH=${PYTHONPATH}:${PWD}
  - pytest -v
