version: '3'
services:
    sea_battle:
        tty: true
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
        environment:
            - "DB_USER=${DB_USER}" 
            - "DB_PASSWORD=${DB_PASSWORD}"
            - "DB_NAME=${DB_NAME}"
            - DB_HOST=db
        volumes:
            - .:/TMS-diploma
            - .env-site-packages:/root/.local/share/virtualenvs/TMS-diploma-NZhI8ys9/lib/python3.6/site-packages
        
    db:
        image: postgres
        ports: 
            - "5432:5432"
        environment:
            - "POSTGRES_USER=${DB_USER}" 
            - "POSTGRES_PASSWORD=${DB_PASSWORD}"
            - "POSTGRES_DB=${DB_NAME}"

    redis:
        image: redis:5.0
        ports:
            - "6379:6379"


    frontend_django:
        tty: true
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        ports:
          - 8080:8080
        volumes:
          - ./frontend:/frontend
        command: "yarn start"
