version: '3'
services:
    sea_battle:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - "DB_USER=${DB_USER}" 
            - "DB_PASSWORD=${DB_PASSWORD}"
            - "DB_NAME=${DB_NAME}"
            - DB_HOST=db
        volumes:
            - .:/TMS-diploma
        
    db:
        image: postgres
        ports: 
            - "5432:5432"
        environment:
            - "POSTGRES_USER=${DB_USER}" 
            - "POSTGRES_PASSWORD=${DB_PASSWORD}"
            - "POSTGRES_DB=${DB_NAME}"
